# Generated by Django 4.0.6 on 2022-07-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='gen',
            new_name='angkatan',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='link_cv',
            new_name='link_cover',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='link_yt',
            new_name='link_youtube',
        ),
    ]
