# Generated by Django 4.0.6 on 2022-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_rename_gen_author_angkatan_rename_name_author_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='program_studi',
            field=models.CharField(default='Ilmu Komputer/Manajemen Informatika', max_length=64),
        ),
    ]
