# Generated by Django 4.0.6 on 2022-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_author_program_studi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deskripsi',
            field=models.TextField(max_length=1000),
        ),
    ]
