# Generated by Django 4.0.6 on 2022-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_project_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_github',
            field=models.CharField(default='https://github.com/', max_length=500),
        ),
    ]
